name: release

on:
  push:
    tags:
      - 'x*'

jobs:
  goreleaser:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
  
      - name: Get OpenWrt firmware
        id: build
        if: (!cancelled())
        run: |
          wget -q -P openwrt-armvirt https://github.com/xrcuo/Actions-OpenWrt-N1/releases/download/immortalwrt/immortalwrt-armsr-armv8-generic-rootfs.tar.gz
      

      - name: Set up Go
        uses: unifreq/openwrt_packit@master
        env:
          WHOAMI: deng
          OPENWRT_ARMVIRT: openwrt-armvirt/*.tar.gz
          PACKAGE_SOC: s905d
          KERNEL_VERSION_NAME: 6.1.80_5.4.269_5.15.150_5.10.210

      - name: Run GoReleaser
        uses: ncipollo/release-action@v1
        with:
          artifacts: ${{ env.PACKAGED_OUTPUTPATH }}/*
          allowUpdates: true
          token: ${{ secrets.GITHDSQ_TOKEN }}
